### ISSUE TITLE
Edit all BSOD text

### ISSUE THREAD

**Issue by NexSqaud** [ch3rn0byl/AngryWindows#1]
It is possible to edit?
`"%d% complete"`
`"For more information about issue..."`
`"If you call a support person..."`
`"Stop code: %s"`
`"What failed: %s"`
`QR Code`

**Comment by ch3rn0byl** [comment]
Yes it is. Those are all going to be under EtwpLastBranchEntry. The QR code itself is an interesting one. It gets replaced when a vmcall is issued. 

Take a look here to see about editing them and what I did to overwrite the main message: https://github.com/ch3rn0byl/AngryWindows/blob/c517240d14b572252a0fc7279415d82a53b5dcb6/AngryWindows/resolve.cpp#L255

I would take into account the length of the strings because then you will start overwriting other areas.

**Comment by exeinfope** [comment]
can i get more info how to remove qrcode? i want to make it

**Comment by exeinfope** [comment]
> can i get more info how to remove qrcode? i want to make it

qword_140C133B8 - map memory and your qrcode will be removed 🍕
